#
#Thu Nov 13 00:39:06 CET 2025
codename1.android.keystore=/home/francesco/eclipse-workspace/protocollo/Keychain.ks
codename1.android.keystoreAlias=galgani
codename1.android.keystorePassword=\!nhudf35ER"\!..hE
codename1.arg.hyp.beamId=5037818e-95e5-40b4-8aca-00f7403ecd27
codename1.arg.ios.newStorageLocation=true
codename1.arg.java.version=8
codename1.arg.maven.codenameone-core.version=7.0.211
codename1.arg.maven.codenameone-maven-plugin=7.0.211
codename1.cssTheme=true
codename1.displayName=Protocollo
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.net.informaticalibera.protocollo
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.kotlin=false
codename1.languageLevel=5
codename1.mainName=Protocollo
codename1.packageName=net.informaticalibera.protocollo
codename1.rim.certificatePassword=
codename1.rim.signtoolCsk=
codename1.rim.signtoolDb=
codename1.secondaryTitle=Hello World
codename1.vendor=Francesco Galgani
codename1.version=1.0
